#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m'

echo -e "${MAGENTA}Pre-push hook...${NC}"

unstaged_changes=$(git diff --name-only)

untracked_files=$(git ls-files --others --exclude-standard)

if [[ -n "$unstaged_changes" || -n "$untracked_files" ]]; then
    echo -e "${RED}Push rejected due to a dirty working tree.${NC}"
    [[ -n "$unstaged_changes" ]] && echo -e "${YELLOW}Unstaged changes:${NC}\n$unstaged_changes"
    [[ -n "$untracked_files" ]] && echo -e "${YELLOW}Untracked files:${NC}\n$untracked_files"
    echo -e "${BLUE}Please commit or stash changes before pushing.${NC}"
    exit 1
fi

echo -e "${GREEN}Working tree is clean.${NC}"

echo -e "${YELLOW}Format checking...${NC}"
deno fmt --check 2> /dev/null
if [ $? -ne 0 ]; then
    echo -e "${RED}Format checking failed.${NC}"
    echo -e "Run ${BLUE}deno fmt --check${NC} to see the issues"
    echo -e "Run ${MAGENTA}deno fmt${NC} for auto formatting"
    exit 1
fi
echo -e "${GREEN}Format checking successful, no format issue!${NC}"


echo -e "${YELLOW}Lint checking...${NC}"
deno lint 2> /dev/null
if [ $? -ne 0 ]; then
    echo -e "${RED}Lint checking failed.${NC}"
    echo -e "Run ${BLUE}deno lint${NC} to see the issues"
    exit 1
fi
echo -e "${GREEN}Lint checking successful, no lint issue!${NC}"


echo -e "${YELLOW}Testing...${NC}"
deno test -A > /dev/null 2> /dev/null
if [ $? -ne 0 ]; then
    echo -e "${RED}Testing failed.${NC}"
    exit 1
fi
echo -e "${GREEN}All tests passed!${NC}"

echo -e "${MAGENTA}Pushing...${NC}"

