# Project Info
sonar.projectKey=seven-wonders
sonar.projectName=seven wonders
sonar.projectVersion=1.0

# SonarQube server info (from secrets)
sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}

# Sources
sonar.sources=src
sonar.exclusions=**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
